export const SET_ADMIN_PAGE_FIELDS = 'SET_ADMIN_PAGE_FIELDS';
export const SUBMIT_ADMIN_CONNECT_FORM = 'UBMIT_ADMIN_CONNECT_FORM';
export const GET_ALL_DOCTOR_APPOINTMENTS = 'GET_ALL_DOCTOR_APPOINTMENTS';
export const SET_ALL_DOCTOR_APPOINTMENTS = 'SET_ALL_DOCTOR_APPOINTMENTS';
export const SET_ALL_USERS = 'SET_ALL_USERS';
export const SUBMIT_NEW_ADMIN_APPOINTMENT = 'SUBMIT_NEW_ADMIN_APPOINTMENT';
